name: Kwiki-PerlTidyModule
version: 0.10
abstract: Kwiki Perl::Tidy Module Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.31
  Kwiki::Cache: 0.10
  Perl::Tidy: 20031021
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
